namespace RootedAndroidGameVM.Core.Debugging;

public sealed record DebugCommandDescription(string Name, string Purpose, string Arguments);
public static class DebugCommandCatalog
{
    public static readonly DebugCommandDescription[] Commands =
    [
        new("status", "当前实例状态", "{}"),
        new("session.summary", "GUI/CLI共用的实例、App、任务、核验、触点、产物与恢复摘要", "{\"package\":\"test.app\",\"refresh\":true}"),
        new("app.page.annotate", "将页面观察关联到30秒内的真实目标应用截图；标明人工观察，不自动推断", "{\"package\":\"test.app\",\"observation\":\"截图编号\",\"page\":\"当前页面说明\"}"),
        new("memory.snapshot", "宿主余量、产品进程工作集/私有提交与归属", "{}"),
        new("capabilities", "能力与约束", "{}"),
        new("schema", "命令说明", "{}"),
        new("start", "启动当前安卓", "{}"),
        new("stop", "同步并停止安卓", "{}"),
        new("window.focus", "打开产品安卓窗口", "{}"),
        new("screen", "保存原始 PNG 和观察编号", "{}"),
        new("preview", "GUI 二进制预览；第二帧为 PNG", "{}"),
        new("preview.benchmark", "预览开销与内存采样", "{\"frames\":20}"),
        new("frames.sample", "应用实际呈现帧时间", "{\"package\":\"test.app\",\"seconds\":15}"),
        new("input", "按观察编号运行输入序列", "{\"observation\":\"id\",\"frames\":[{\"atMs\":0,\"touches\":[{\"id\":0,\"x\":100,\"y\":100,\"pressure\":1}]}]}"),
        new("release", "取消输入并释放触点", "{}"),
        new("wake", "唤醒并验证状态", "{}"),
        new("key", "Android 键码", "{\"key\":\"KEYCODE_BACK\"}"),
        new("clipboard", "读取或写入安卓剪贴板", "{\"text\":\"可选写入内容\"}"),
        new("apps", "第三方应用列表", "{}"),
        new("apps.list", "真实名称/图标、用户和安装身份的应用目录；支持搜索和分页", "{\"userId\":0,\"query\":\"\",\"includeSystem\":false,\"includeIcons\":false,\"pageSize\":100}"),
        new("apps.resolve", "重新核对应用引用的实例、用户和安装身份", "{\"appRef\":\"apps.list返回的引用\"}"),
        new("users.list", "Android用户及解锁状态", "{}"),
        new("files.roots", "真实根目录及存在/锁定/creatable状态；未生成的外部应用根可显式规划初始化", "{\"appRef\":\"应用引用，可省略以查看共享存储\",\"userId\":0}"),
        new("files.browse", "批量读取结构化目录页；使用下一游标继续，目录变化须重读", "{\"rootRef\":\"根引用\",\"relativePath\":\"\",\"pageSize\":200}"),
        new("files.stat", "验证条目身份并读取元数据，可选计算文件SHA-256", "{\"entryRef\":\"文件引用\",\"hash\":true}"),
        new("files.transfer.plan", "只读多选计划；source.targetName指定名称，contentsOnly上传目录内容，createParents规划缺失的应用外部根与父目录", "{\"direction\":\"download\",\"sources\":[{\"entryRef\":\"条目引用\"}],\"destination\":{\"localDirectory\":\"D:\\\\Exports\"}}"),
        new("files.transfer.inspect", "分页读取持久传输计划；计划不代表已复制", "{\"planId\":\"计划编号\",\"offset\":0,\"pageSize\":100}"),
        new("files.transfer.list", "最近计划及明确执行状态/恢复入口", "{}"),
        new("files.tools.list", "最近guest工具归属、清理证据与待恢复记录", "{}"),
        new("files.tools.cleanup", "关闭指定请求的启动门并核实同会话guest工具已退出；不重放写入", "{\"token\":\"guest工具记录中的token\"}"),
        new("tools.list", "文件、应用元数据及诊断的guest工具与资源清理记录", "{}"),
        new("tools.cleanup", "按实例/会话核实工具和诊断资源清理；不重放原请求", "{\"token\":\"工具归属记录中的token\"}"),
        new("files.transfer.start", "按计划执行分块传输；重复幂等键返回原任务", "{\"planId\":\"计划编号\",\"idempotencyKey\":\"本次执行唯一键\",\"conflictPolicy\":\"overwrite\",\"stopApplications\":true}"),
        new("files.transfer.resume", "核对源、目标和暂存后明确续作，不自动重放", "{\"planId\":\"计划编号\",\"idempotencyKey\":\"本次续作唯一键\"}"),
        new("apk.inspect", "APK 版本、包名与 ABI", "{\"path\":\"C:\\\\input\\\\app.apk\"}"),
        new("install", "保留数据安装并启动，不降级", "{\"path\":\"C:\\\\input\\\\app.apk\"}"),
        new("launch", "启动并观察进程；waitForActivity可等待前台Activity，均不代表页面可操作", "{\"package\":\"test.app\",\"waitForActivity\":true}"),
        new("app.observe", "保存进程与前台Activity观察证据和时间", "{\"package\":\"test.app\"}"),
        new("force-stop", "停止应用", "{\"package\":\"test.app\"}"),
        new("uninstall", "明确确认后卸载普通应用", "{\"package\":\"test.app\",\"confirm\":true}"),
        new("files.list", "共享浏览器兼容列表，默认全部；可用pageSize/cursor分页，shared根仍为Download", "{\"package\":\"test.app\",\"scope\":\"external\",\"remote\":\"files\"}"),
        new("files.push", "暂存、校验与备份后上传", "{\"package\":\"test.app\",\"scope\":\"external\",\"remote\":\"files/a.bin\",\"local\":\"C:\\\\input\\\\a.bin\"}"),
        new("files.pull", "校验后下载文件", "{\"package\":\"test.app\",\"scope\":\"external\",\"remote\":\"files/a.bin\",\"local\":\"C:\\\\output\\\\a.bin\"}"),
        new("files.export", "受控导出选中目录", "{\"package\":\"test.app\",\"scope\":\"private\",\"remote\":\"files\",\"local\":\"C:\\\\output\"}"),
        new("files.diff", "目录差异比较", "{\"package\":\"test.app\",\"scope\":\"external\",\"remote\":\"files/qa\",\"local\":\"C:\\\\qa\"}"),
        new("files.sync", "同步变化文件并保留额外文件", "{\"package\":\"test.app\",\"scope\":\"external\",\"remote\":\"files/qa\",\"local\":\"C:\\\\qa\"}"),
        new("logs", "跟随应用 PID 的日志", "{\"package\":\"test.app\",\"seconds\":30}"),
        new("metrics", "内存、CPU 与可用诊断依据", "{\"package\":\"test.app\"}"),
        new("record", "录屏，无音频", "{\"seconds\":15}"),
        new("trace", "系统追踪", "{\"seconds\":15}"),
        new("checkpoint.create", "停机磁盘检查点", "{}"),
        new("checkpoint.list", "检查点列表", "{}"),
        new("checkpoint.restore", "验证后恢复并冷启动", "{\"id\":\"checkpoint-id\"}"),
        new("checkpoint.recover", "恢复中断切换", "{}"),
        new("runtime.inspect", "请求配置与实际显示分开报告", "{}"),
        new("runtime.configure", "停机后保存配置", "{\"profile\":{\"renderer\":\"host\",\"width\":1920,\"height\":1080,\"density\":240,\"refreshRate\":120,\"memoryMb\":3072,\"cpuCores\":4,\"desktopDisplay\":true}}"),
        new("paths.inspect", "资源根、SDK、AVD 与下载缓存的实际位置及来源（产品自管或外部复用）", "{}"),
        new("paths.configure", "停机后保存 SDK/AVD/下载缓存位置；传 null 恢复产品默认，外部 SDK 以核验方式使用", "{\"sdkRoot\":\"D:\\\\Android\\\\Sdk\",\"avdHome\":null,\"downloadCache\":null}"),
        new("downloads.list", "安装所需组件清单：文件名、URL、SHA-256、大小与缓存校验状态", "{}"),
        new("downloads.import", "从本地文件夹导入已下载组件，按 SHA-256 校验后写入下载缓存", "{\"folder\":\"D:\\\\rgvm-downloads\"}"),
        new("downloads.mirror", "设置下载镜像：preset:\"china\" 用国内预设，rules 自定义前缀，clear:true 恢复直连；仍强制 SHA-256 校验", "{\"preset\":\"china\"}"),
        new("display.desktop", "切换已备份的模拟设备外观", "{\"enabled\":true}"),
        new("performance.set", "兼容旧版图形档位", "{\"profile\":\"HighPerformance\"}"),
        new("shell", "有界前台Shell，保持shell UID并清理所属子进程", "{\"script\":\"id\",\"timeoutSeconds\":10}"),
        new("root-shell", "有界前台Root Shell，结束后清理所属子进程", "{\"script\":\"id\",\"timeoutSeconds\":10}"),
        new("test", "顺序测试请求，不允许嵌套恢复", "{\"steps\":[{\"command\":\"screen\"}]}"),
        new("grpc.audit", "检查认证拒绝与回环连接", "{}"),
        new("licenses", "随程序附带的许可证", "{}"),
        new("jobs", "任务列表", "{}"),
        new("job", "查询并续期输入任务", "{\"id\":\"job-id\"}"),
        new("cancel", "取消任务", "{\"id\":\"job-id\"}"),
        new("quiesce", "停止调试任务但保留安卓", "{}"),
        new("shutdown", "安卓已停止时退出协调进程", "{}")
    ];
}
